"""Refinement chip schema and structured turn-confidence signal.

Clarification is blocking: the agent should ask before recommending when the
reference cannot be resolved.  Refinement is non-blocking: the agent can still
recommend, and offers follow-up chips afterwards.

Chip CONTENT is no longer produced here.  It is generated by the LLM from the
full turn context after the slate is known (services/refinement_generator.py),
per the LLM-first principle: no keyword lists, no fixed profile mappings, no
generic template options.  This module keeps only the shared schema and an
operational confidence derived from structured plan fields.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from schemas.dialog_state import DialogMusicState, load_dialog_state
from schemas.query_plan import MusicQueryPlan


class RefinementOption(BaseModel):
    """A single non-blocking follow-up chip."""

    label: str
    prompt: str
    reason: str = ""
    source: str = "context"


class RefinementSuggestion(BaseModel):
    """Soft-confidence report for the current turn."""

    confidence: float = 1.0
    reason: str = ""
    options: list[RefinementOption] = Field(default_factory=list)


def build_refinement_suggestions(
    *,
    user_input: str,
    plan: MusicQueryPlan | None,
    dialog_state: DialogMusicState | dict[str, Any] | None = None,
) -> RefinementSuggestion:
    """Return a conservative turn confidence from structured plan fields only.

    The confidence is not a model probability.  It is an operational signal:
    high means "route and constraints are concrete"; medium means "recommend
    now, but chips may help"; low is reserved for blocking clarification,
    which is handled elsewhere.  Options are always empty here — chips are
    generated post-slate by the LLM (services/refinement_generator.py).
    """
    del user_input  # confidence must not depend on keyword-matching free text
    if plan is None or plan.intent_type in {"general_chat", "acquire_music", "recommend_by_favorites"}:
        return RefinementSuggestion()

    state = load_dialog_state(dialog_state)
    rp = plan.retrieval_plan
    hard = rp.hard_constraints
    soft = rp.soft_intent
    hints = rp.hints

    has_soft_signal = bool(
        soft.goal or soft.trajectory or soft.vibe or soft.avoid
        or hints.genres or hints.mood or hints.scenario
    )

    confidence = 0.86
    reason = "concrete_constraints"
    if has_soft_signal:
        confidence = 0.66
        reason = "soft_intent_open_ended"
    if state.last_delta.followup:
        confidence = max(confidence, 0.72)
    if hard.language or hints.genres:
        confidence = max(confidence, 0.7)

    return RefinementSuggestion(confidence=round(confidence, 2), reason=reason)
